### ISSUE TITLE
InvalidOperationException is thrown from RunStarting event handler

### ISSUE THREAD

**Issue by ideafixxxer** [TestCentric/testcentric-gui#333]
After clicking Run button the following event handler gets invoked:
``` C#
            _model.Events.RunStarting += (e) =>
            {
                (_view.Tree.TopNode as TestSuiteTreeNode)?.ClearResults();
                _view.RunCommand.Enabled = false;
                _view.CheckPropertiesDialog();
            };
```
Accessing property `TreeViewElement.TopNode` throws the following exception:
`System.InvalidOperationException: 'Cross-thread operation not valid: Control 'treeView1' accessed from a thread other than the thread it was created on.'`
This exception is not visible to the end user but prevents the following lines from executing.

**Comment by ideafixxxer** [comment]
Same issue on `TestEventDispatcher.FireTestsChanged`. 
```
System.InvalidOperationException: Cross-thread operation not valid: Control 'treeView1' accessed from a thread other than the thread it was created on.
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, Int32 lparam)
   at System.Windows.Forms.TreeView.get_TopNode()
   at TestCentric.Gui.Elements.TreeViewElement.get_TopNode() in C:\Users\U6072228\Source\Repos\testcentric-gui\src\Common\components\Elements\TreeViewElement.cs:line 113
   at TestCentric.Gui.VisualState.LoadFrom(ITestTreeView view) in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestCentric\testcentric.gui\VisualState.cs:line 82
   at TestCentric.Gui.Presenters.TreeViewPresenter.<>c__DisplayClass9_0.<WireUpEvents>b__2(TestEventArgs e) in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestCentric\testcentric.gui\Presenters\TreeViewPresenter.cs:line 117
   at TestCentric.Gui.Model.TestEventHandler.Invoke(TestEventArgs args)
   at TestCentric.Gui.Model.TestEventDispatcher.FireTestsReloading() in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestModel\model\TestEventDispatcher.cs:line 65
   at TestCentric.Gui.Model.TestModel.ReloadTests() in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestModel\model\TestModel.cs:line 231
   at TestCentric.Gui.Presenters.TreeViewPresenter.<>c__DisplayClass9_0.<WireUpEvents>b__4(TestEventArgs e) in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestCentric\testcentric.gui\Presenters\TreeViewPresenter.cs:line 139
   at TestCentric.Gui.Model.TestEventDispatcher.FireTestChanged() in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestModel\model\TestEventDispatcher.cs:line 75
   at TestCentric.Gui.Model.TestModel.<LoadAllTests>b__69_0(String path) in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestModel\model\TestModel.cs:line 203
   at TestCentric.Gui.Model.AssemblyWatcher.PublishEvent() in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestModel\model\AssemblyWatcher.cs:line 152
   at TestCentric.Gui.Model.AssemblyWatcher.OnTimer(Object source, ElapsedEventArgs e) in C:\Users\U6072228\Source\Repos\testcentric-gui\src\TestModel\model\AssemblyWatcher.cs:line 124
   at System.Timers.Timer.MyTimerCallback(Object state)
```
The first issue is fixed (PR was opened)
