### ISSUE TITLE
Test-Centric Gui cannot reconnect to a website after a finished round of tests using selenium

### ISSUE THREAD

**Issue by qqjjz** [TestCentric/testcentric-gui#383]
When testing a project that uses Selenium 3 webdriver to connect to a website and perform automated tests, the GUI won't reconnect after the webdriver closes down upon completing the last test.  If the GUI window remains open and testing is attempted again, the following error is displayed:

```
SA3.AutomatedTests.TestStructure.SampleTesting.SampleTest:
OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:54574
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
```

To continue testing, the window must be closed and then reopened.

**Comment by CharliePoole** [comment]
This would seem to indicate that you are not completely disposing of the driver. Can you show us the initialization and teardown code?

**Comment by CharliePoole** [comment]
Closing as @qqjjz hasn't responded.
