### ISSUE TITLE
Cannot run the tests in TestCentric.Gui.Model.Tests.dll more than once

### ISSUE THREAD

**Issue by mikkelbu** [TestCentric/testcentric-gui#39]
If I open TestCentric.Gui.Model.Tests.dll and run the tests then they all succeed, but if I try to do it again (without reloading the tests) then I get the following failure
```
TestCentric.Gui.Model.AvailableRuntimesTest (TestFixtureSetUp):
System.Runtime.Remoting.RemotingException : Found two different objects associated with the same URI, '/f6fa6185_ed56_455a_8421_ab43dcc4192d/TestAgency'.
```
with the stacktrace
```
at System.Runtime.Remoting.IdentityHolder.SetIdentity(Identity idObj, String URI, DuplicateIdentityOption duplicateOption)
at System.Runtime.Remoting.IdentityHolder.FindOrCreateServerIdentity(MarshalByRefObject obj, String objURI, Int32 flags)
at System.Runtime.Remoting.RemotingServices.GetOrCreateIdentity(MarshalByRefObject Obj, String ObjURI, Boolean isInitializing)
at System.Runtime.Remoting.RemotingServices.MarshalInternal(MarshalByRefObject Obj, String ObjURI, Type RequestedType, Boolean updateChannelData, Boolean isInitializing)
at System.Runtime.Remoting.RemotingServices.MarshalInternal(MarshalByRefObject Obj, String ObjURI, Type RequestedType)
at System.Runtime.Remoting.RemotingServices.Marshal(MarshalByRefObject Obj, String URI)
at NUnit.Engine.Internal.ServerBase.Start()
at NUnit.Engine.Services.TestAgency.StartService()
at NUnit.Engine.Services.ServiceManager.StartServices()
at NUnit.Engine.TestEngine.Initialize()
at NUnit.Engine.TestEngine.NUnit.Engine.ITestEngine.get_Services()
at TestCentric.Gui.Model.TestServices..ctor(ITestEngine testEngine) in C:\src\NUnit\test-centric-gui\src\TestModel\model\TestServices.cs:line 42
at TestCentric.Gui.Model.TestModel..ctor(ITestEngine testEngine) in C:\src\NUnit\test-centric-gui\src\TestModel\model\TestModel.cs:line 45
at TestCentric.Gui.Model.AvailableRuntimesTest.CreateTestModel() in C:\src\NUnit\test-centric-gui\src\TestModel\tests\AvailableRuntimesTest.cs:line 41
```

**Comment by CharliePoole** [comment]
@mikkelbu You forgot to say how you're running the tests. 😸 However, I can see it's caused by starting the TestAgency more than once, which is a long-time no-no. This limitation plagues our engine tests and, since we are using the engine, we have to deal with it as well.

**Comment by mikkelbu** [comment]
@CharliePoole  I ran the tests using the GUI - of course 😄 .

**Comment by immeraufdemhund** [comment]
No one can ever accuse us of not eating our own dog food.

**Comment by CharliePoole** [comment]
I finally got around to running this and I confirm it is a bug. It's not an important bug for the GUI - it's actually a test bug - but it's high priority because it makes CI fail.

Quick fix (if we need to) would be to Ignore the test.

Best fix would be to mock the engine, returning a set of runtimes as they engine would and verifying they are correctly filtered by the model. In fact, that would be a better test and would be testing the model rather than the model plus engine.
