### ISSUE TITLE
1.4.0 Unhandled exception

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#579]
Hello,

When I open my .dll with v1.4.0 I get an unhandled exception:

System.FormatException: 'Input string was not in a correct format.'

System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at TestCentric.Engine.Services.RuntimeFrameworkService.FindDotNetCoreFrameworks()
   at TestCentric.Engine.Services.RuntimeFrameworkService.StartService()
   at TestCentric.Engine.Services.ServiceManager.StartServices()
   at TestCentric.Engine.TestEngine.Initialize()
   at TestCentric.Engine.TestEngine.NUnit.Engine.ITestEngine.get_Services()
   at TestCentric.Gui.Model.TestServices..ctor(ITestEngine testEngine)
   at TestCentric.Gui.Model.TestModel..ctor(ITestEngine testEngine, String applicationPrefix)
   at TestCentric.Gui.Model.TestModel.CreateTestModel(ITestEngine testEngine, CommandLineOptions options)
   at TestCentric.Gui.AppEntry.Main(String[] args)
   at TestCentric.Gui.Class1.Main(String[] args)

**Comment by CharliePoole** [comment]
What is your platform, Windows? Linux?

Does this happen no matter what assembly you try to open or just for some targets? It looks like it would be for all but please check.

The stack indicates that it's happening in the initialization, when we search to see what .NET Core frameworks are installed. Please look at the directory `C:\Program Files\dotnet\shared\Microsoft.NETCore.App` (windows) or `/usr/shared/dotnet/Microsoft.NETCore.App` (linux) and list for me all the subdirectories you find.

**Comment by MartinZec** [comment]
I use Windows.
I have 3 assemblies, it happens for all.

attached a screenshot of my folder:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App
![dot_net](https://user-images.githubusercontent.com/44475413/80978754-c304e200-8e26-11ea-9640-9536816e931d.png)

**Comment by CharliePoole** [comment]
OK. The code assumes that all the directories names are valid versions. They all are but one of them has a pre-rellease suffix. The code assumes the name can be parsed by the `Version` class and throws an exception. I'm marking this as a critical bug and will fix it in the 1.4.1 release.

As a workaround, you can 
 * Uninstall that version if you no longer need it OR
 * Remove the directory OR
 * Rename the directory

No guarantee that the second or third choices won't break something in Windows, so back it up first.

If you try any of the above, please post here what happened.

**Comment by MartinZec** [comment]
Removing the directory works as a workaround.

**Comment by CharliePoole** [comment]
Since there's a workaround, I'm downgrading this from Critical to High priority. That means there will be a fix in the next version of the GUI (1.4.1) but there won't be an emergency release right now.

If anyone encounters this error please try the steps above and report your success or lack of it here!
