### ISSUE TITLE
Exception "Cross-thread operation not valid: Control 'progressBar' accessed from a thread other than the thread it was created on."

### ISSUE THREAD

**Issue by ManfredLange** [TestCentric/testcentric-gui#76]
# Steps To Reproduce

1. Build latest commit from master (95aa1bb)
2. Run the Gui under debugger to make it easier to run into the exception
3. Load an assembly containing tests => works fine, i.e. discovers all tests as expected
4. Select a single test and select "Run" from context menu => Exception

# Exception Details
## Exception Message
"Cross-thread operation not valid: Control 'progressBar' accessed from a thread other than the thread it was created on."
## Stack Trace

   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.Invalidate(Boolean invalidateChildren)
   at System.Windows.Forms.Control.Refresh()
   at TestCentric.Gui.Controls.ColorProgressBar.OnForeColorChanged(EventArgs e) in C:\projects\testcentric\testcentric-gui\src\TestCentric\testcentric.gui\Controls\ProgressBar.cs:line 248
   at System.Windows.Forms.Control.set_ForeColor(Color value)
   at TestCentric.Gui.Controls.TestProgressBar.Initialize(Int32 testCount) in C:\projects\testcentric\testcentric-gui\src\TestCentric\testcentric.gui\Controls\ProgressBar.cs:line 366
   at TestCentric.Gui.Controls.TestProgressBar.<>c__DisplayClass7_0.<InitializeView>b__3(RunStartingEventArgs e) in C:\projects\testcentric\testcentric-gui\src\TestCentric\testcentric.gui\Controls\ProgressBar.cs:line 393

**Comment by drSte** [comment]
i can try to take a look at this

**Comment by CharliePoole** [comment]
That will be great.
