### ISSUE TITLE
NRE when starting the GUI

### ISSUE THREAD

**Issue by mikkelbu** [TestCentric/testcentric-gui#93]
I just tried to compile the GUI from master and ran into a NRE when starting the gui.

![image](https://user-images.githubusercontent.com/1007631/43995222-95056f28-9daa-11e8-9bbe-f8444ce7872e.png)

Stacktrace
```csharp
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=TestCentric.Gui.Runner
  StackTrace:
   at TestCentric.Gui.Controls.TestSuiteTreeView.set_CheckBoxes(Boolean value) in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\Controls\TestSuiteTreeView.cs:line 172
   at TestCentric.Gui.Controls.TestTree.set_ShowCheckBoxes(Boolean value) in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\Controls\TestTree.cs:line 123
   at TestCentric.Gui.Controls.TestTree.InitializeView(ITestModel model, TestCentricPresenter presenter) in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\Controls\TestTree.cs:line 718
   at TestCentric.Gui.TestCentricPresenter.InitializeControls(Control owner) in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\TestCentricPresenter.cs:line 478
   at TestCentric.Gui.TestCentricPresenter.InitializeControls(Control owner) in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\TestCentricPresenter.cs:line 480
   at TestCentric.Gui.TestCentricPresenter.OnStartup() in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\TestCentricPresenter.cs:line 97
   at TestCentric.Gui.TestCentricMainForm.NUnitForm_Load(Object sender, EventArgs e) in C:\src\NUnit\test-centric-gui\src\TestCentric\testcentric.gui\TestCentricMainForm.cs:line 1100
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
...
```
The problem is that `Model` is null in `                    Model.Services.UserSettings.Gui.TestTree.ShowCheckBoxes = base.CheckBoxes = value;` as `InitializeView` has not been called yet. I think that this was introduced by #89

**Comment by CharliePoole** [comment]
I saw this and then no longer did after I changed a few settings. I can't get the error back! This is all pretty dependent on the default settings so I guess we need more tests. It may be possible to port some of the extensive tests of the gui portion from the experimental GUI.

If #89 did this, then it's in the release, so we need a quick repair. I was able to get the error after installing alpha1 and then, changing settings, lost it again. But it's still a priority.

@mikkelbu Looking further into this but leaving unassigned in case you want to investigate further.

**Comment by CharliePoole** [comment]
@mikkelbu `TestCentricPresenter.InitializeControls` looks like it might be the culprit.  I added the comments in this snippet...

        // Initially called on the Form itself
        private void InitializeControls(Control owner)
        {
            foreach (Control control in owner.Controls)
            {
                var view = control as IViewControl;

                // If the control is a view, initialize it.
                if (view != null)
                    view.InitializeView(Model, this);
                
                // Recurse to handle nested controls
                InitializeControls(control);
            }
        }

At least for the purposes of setting the Model, we should do the nested controls first, in case the higher level initialization calls something that requires it. However, we would have to look carefully to ensure that no subordinate control sets properties in its parent!

Ideally, each control would be independent, whether nested or not. That way, you can move things around in the designer without changing the code.

I believe they are, in almost all cases, the exception being TestTree / TestSuiteTreeView, which are interdependent in V2 and may still be so here. Given a choice, I prefer that a control know about it's contents and not about its container!

**Comment by mikkelbu** [comment]
@CharliePoole my settings are as follows. I'm quite busy at the moment, so I probably will not have time to look into this, so I don't mind that you do the investigation 😄 

```xml
<?xml version="1.0"?>
<NUnitSettings>
  <Settings>
    <Setting name="Engine.Options.Agents" value="0" />
    <Setting name="Engine.Options.DomainUsage" value="Multiple" />
    <Setting name="Engine.Options.PrincipalPolicy" value="UnauthenticatedPrincipal" />
    <Setting name="Engine.Options.ProcessModel" value="Multiple" />
    <Setting name="Engine.Options.ReloadOnChange" value="True" />
    <Setting name="Engine.Options.ReloadOnRun" value="False" />
    <Setting name="Engine.Options.RerunOnChange" value="False" />
    <Setting name="Engine.Options.SetPrincipalPolicy" value="False" />
    <Setting name="Engine.Options.ShadowCopyFiles" value="True" />
    <Setting name="Gui.DisplayFormat" value="Full" />
    <Setting name="Gui.ErrorDisplay.SourceCodeDisplay" value="False" />
    <Setting name="Gui.InitialSettingsPage" value="Gui.General" />
    <Setting name="Gui.MainForm.Font" value="Microsoft Sans Serif, 8.25pt" />
    <Setting name="Gui.MainForm.Height" value="1030" />
    <Setting name="Gui.MainForm.Left" value="950" />
    <Setting name="Gui.MainForm.Location" value="-7, 0" />
    <Setting name="Gui.MainForm.Maximized" value="False" />
    <Setting name="Gui.MainForm.Size" value="654, 687" />
    <Setting name="Gui.MainForm.SplitPosition" value="366" />
    <Setting name="Gui.MainForm.Top" value="0" />
    <Setting name="Gui.MainForm.Width" value="980" />
    <Setting name="Gui.MiniForm.Height" value="400" />
    <Setting name="Gui.MiniForm.Left" value="10" />
    <Setting name="Gui.MiniForm.Maximized" value="True" />
    <Setting name="Gui.MiniForm.Top" value="10" />
    <Setting name="Gui.MiniForm.Width" value="700" />
    <Setting name="Gui.Options.DisplayFormat" value="Full" />
    <Setting name="Gui.Options.Font" value="Microsoft Sans Serif, 8.25pt" />
    <Setting name="Gui.Options.InitialSettingsPage" value="Gui.Project Editor" />
    <Setting name="Gui.Options.LoadLastProject" value="True" />
    <Setting name="Gui.Options.ProjectEditorPath" value="C:\Windows\notepad.exe" />
    <Setting name="Gui.Options.SelectedTab" value="0" />
    <Setting name="Gui.RecentProjects.CheckFilesExist" value="True" />
    <Setting name="Gui.RecentProjects.File1" value="C:\Users\Mikkel\Source\Repos\ClassLibrary12\ClassLibrary12\bin\Debug\net471\ClassLibrary12.dll" />
    <Setting name="Gui.RecentProjects.File10" value="X:\src\NUnit\test-centric-gui\bin\Debug\TestCentric.Gui.Model.Tests.dll" />
    <Setting name="Gui.RecentProjects.File2" value="C:\src\NUnit\nunit-console\bin\Release\nunit3-console.tests.dll" />
    <Setting name="Gui.RecentProjects.File3" value="X:\src\NUnit\nunit-console\bin\Release\EngineTests.nunit" />
    <Setting name="Gui.RecentProjects.File4" value="C:\src\NUnit\nunit-console\bin\Release\ConsoleTests.nunit" />
    <Setting name="Gui.RecentProjects.File5" value="X:\src\NUnit\nunit-console\bin\Release\nunit.engine.tests.dll" />
    <Setting name="Gui.RecentProjects.File6" value="X:\Temp\MultipleDlls.nunit" />
    <Setting name="Gui.RecentProjects.File7" value="X:\Temp\NunitExample.nunit" />
    <Setting name="Gui.RecentProjects.File8" value="X:\src\NUnit\test-centric-gui\bin\Debug\TestCentric.Gui.Tests.dll" />
    <Setting name="Gui.RecentProjects.File9" value="X:\src\NUnit\nunit\nunit.sln" />
    <Setting name="Gui.RecentProjects.MaxFiles" value="5" />
    <Setting name="Gui.ResultTabs.TextOutput.Labels" value="ON" />
    <Setting name="Gui.Settings.InitialPage" value="GuiSettingsPage" />
    <Setting name="Gui.TestTree.InitialTreeDisplay" value="0" />
    <Setting name="Gui.TestTree.SaveVisualState" value="False" />
    <Setting name="Gui.TestTree.ShowCheckBoxes" value="True" />
    <Setting name="Options.CheckFilesExist" value="True" />
    <Setting name="Options.CheckFIlesExist" value="True" />
    <Setting name="Options.InternalTraceLevel" value="Debug" />
    <Setting name="Options.LoadLastProject" value="True" />
    <Setting name="Options.MaxFiles" value="6" />
    <Setting name="Options.ShowCheckBoxes" value="False" />
    <Setting name="Options.TestLoader.Agents" value="6" />
    <Setting name="Options.TestLoader.AutoNamespaceSuites" value="True" />
    <Setting name="Options.TestLoader.ClearResultsOnReload" value="False" />
    <Setting name="Options.TestLoader.DomainUsage" value="Multiple" />
    <Setting name="Options.TestLoader.PrincipalPolicy" value="NoPrincipal" />
    <Setting name="Options.TestLoader.ProcessModel" value="Multiple" />
    <Setting name="Options.TestLoader.ReloadOnChange" value="True" />
    <Setting name="Options.TestLoader.ReloadOnRun" value="False" />
    <Setting name="Options.TestLoader.RerunOnChange" value="False" />
    <Setting name="Options.TestLoader.SetPrincipalPolicy" value="True" />
    <Setting name="Options.TestLoader.ShadowCopyFiles" value="True" />
    <Setting name="TestCentric.ClearResultsOnReload" value="False" />
    <Setting name="TestCentric.DisplayFormat" value="Mini" />
    <Setting name="TestCentric.FixedFont" value="Courier New, 8pt" />
    <Setting name="TestCentric.Font" value="Microsoft Sans Serif, 8.25pt" />
    <Setting name="TestCentric.InitialSettingsPage" value="TestCentric.General" />
    <Setting name="TestCentric.LoadLastProject" value="True" />
    <Setting name="TestCentric.SelectedTab" value="0" />
    <Setting name="TestCentric.Settings.InitialPage" value="ProjectEditorSettingsPage" />
  </Settings>
</NUnitSettings>
```

**Comment by stlegros** [comment]
Hi, guys,
I just meet this problem with checkboxes today; I tried to reinstall all the app and it don't work (I have always the dialog with the exception). Can we reset the app to default settings to get around this bug until your next release? How can we do this?
Thank you for the nice app!

**Comment by mikkelbu** [comment]
Hi @stlegros
You can "reset" your setting by moving/deleting the file `Nunit30Settings.xml` in `C:\Users\USERNAME\AppData\Local\NUnit`. E.g. paste the content of the file into this issue and we can use that to diagnose the problem.
