### ISSUE TITLE
TestCentric.GuiRunner 2.0.0-beta1: no agents in zip package

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#985]
I downloaded:
https://github.com/TestCentric/testcentric-gui/releases/download/2.0.0-beta1/TestCentric.GuiRunner-2.0.0-beta1.zip

After unzipping, there was no agent folder as it was for the alpha releases.
When I load my tests, I see:

runstate='NotRunnable' 

NUnit.Engine.NUnitEngineException : No agent can be found for package test.dll

--NUnitEngineExceptionagent can be found for package test.dll.
  at TestCentric.Engine.Runners.AssemblyRunner.CreateAgentAndRunnerIfNeeded()
  at TestCentric.Engine.Runners.AssemblyRunner.Explore(TestFilter filter)

**Comment by CharliePoole** [comment]
@MartinZec This is partly explained in the release itself: https://github.com/TestCentric/testcentric-gui/releases/tag/2.0.0-beta1

Of course, in the case of the zip file, there is no such thing as a "dependency" so you have to install the agent extensions yourself. That should be explained somewhere of course. I'll come back shortly with some instructions - after I try it out myself. :-)

**Comment by CharliePoole** [comment]
@MartinZec Installation of agents for the zip package...

1. Install the zip as you normally do into TARGET_DIR
2. Make a subdirectory TARGET_DIR/bin/addins
3. Change into that new directory
4. Issue NuGet commands (assuming NUGET is on your path)

```
nuget install NUnit.Extension.Net462PluggableAgent -Version 2.0.1
nuget install NUnit.Extension.Net60PluggableAgent -Version 2.0.0
nuget install NUnit.Extension.Net70PluggableAgent -Version 2.0.0
```

This will give you the "standard" set of agents. Note that version 2.0.0 of the net462 agent is broken, so 2.0.1 is required.

You can vary the agents you install based on what you need, of course. Just check to see what the latest version is.

After you try this out, I'd appreciate your input on whether you think the zip package is really needed. You could easily install the gui wherever you want using the nuget command-line and that would bring down the agents automatically.

**Comment by MartinZec** [comment]
@CharliePoole  Thank you for the explanation, it worked after loading the PluggableAgents.

Since the zipped package has still the requirement to load other packages, I think it is not needed. Nuget or chocolatey should be sufficient.

**Comment by CharliePoole** [comment]
That was my thinking as well. If I kept the zip, I think I would need to expand it to include agents but it's already a bit of extra work to maintain. I'll start a new issue about that to see if there are comments.

**Comment by CharliePoole** [comment]
Added install instructions to the Release info. Created #986
